import React from 'react';

interface PrintTemplateProps {
    title: string;
    subtitle?: string;
    content: React.ReactNode;
    officialHeader?: boolean;
}

export const PrintTemplate: React.FC<PrintTemplateProps> = ({ title, subtitle, content, officialHeader = true }) => {
    return (
        <div className="print-template bg-white text-black font-sans" dir="rtl">
            <style>{`
                @media print {
                    @page { margin: 20mm; }
                    body { background: white !important; color: black !important; -webkit-print-color-adjust: exact; print-color-adjust: exact; font-size: 11pt; line-height: 1.6; margin: 0; padding: 0; }
                    .no-print { display: none !important; }
                    .print-template { max-width: 100%; margin: 0; padding: 0; box-shadow: none; }
                    table { width: 100%; border-collapse: collapse; margin-bottom: 2rem; }
                    th, td { border: 1px solid #e2e8f0; padding: 12px; text-align: right; }
                    th { background-color: #f8fafc !important; color: #1e293b; font-weight: bold; }
                    * { overflow-wrap: break-word; }
                }
                .print-template { max-width: 210mm; margin: 0 auto; background: white; padding: 40px; }
             `}</style>

            {officialHeader && (
                <div className="flex justify-between items-start border-b-4 border-black pb-8 mb-10">
                    <div className="flex items-center gap-4">
                        <img src="/logo.png" alt="Logo" className="w-16 h-16 object-contain" />
                        <div>
                            <h1 className="text-3xl font-black uppercase tracking-tight leading-none mb-1">E-TASHLEH</h1>
                            <p className="text-[10px] text-gray-500 font-bold tracking-widest uppercase">Governance Platform</p>
                        </div>
                    </div>
                    
                    <div className="text-left flex flex-col items-end">
                        <div className="bg-black text-white px-4 py-1 text-[10px] font-bold uppercase tracking-widest rounded-sm mb-4 shadow-sm">
                            OFFICIAL CERTIFIED REPORT
                        </div>
                        <h2 className="text-2xl font-black uppercase leading-tight">{title}</h2>
                        {subtitle && <p className="text-sm text-gray-600 font-bold mt-1 uppercase tracking-widest">{subtitle}</p>}
                    </div>
                </div>
            )}

            {officialHeader && (
                <div className="flex justify-between text-[10px] font-bold text-gray-500 uppercase tracking-widest mb-10">
                    <div className="flex gap-8">
                        <div>
                            <span className="block text-[8px] text-gray-400 mb-0.5">DOCUMENT DATE</span>
                            {new Date().toLocaleDateString('ar-EG')}
                        </div>
                        <div>
                            <span className="block text-[8px] text-gray-400 mb-0.5">GENERATED AT</span>
                            {new Date().toLocaleTimeString('ar-EG')}
                        </div>
                    </div>
                </div>
            )}

            <div className="document-body">
                {content}
            </div>

            <div className="mt-20 border-t-2 border-gray-200 pt-8 flex justify-between items-start">
                <div className="text-[10px] text-gray-500 space-y-2 max-w-lg">
                    <p className="font-bold text-black text-xs">© 2026 E-TASHLEH ECOSYSTEM. ALL RIGHTS RESERVED.</p>
                    <p className="leading-relaxed text-gray-600">هذا المستند مشفر وموثق إلكترونياً وصادر من نظام الحوكمة المركزي لمنصة إي تشليح. لا يتطلب توقيعاً خطياً أو ختماً يدوياً للاعتداد به في المعاملات الداخلية والمراجعات التقنية.</p>
                    <p className="text-[9px] text-gray-400">This is an electronically encrypted and certified document generated by the E-TASHLEH Central Governance System. No manual signature required.</p>
                </div>
                
                <div className="text-center border-r-2 border-gray-100 pr-8">
                    <div className="w-16 h-16 border-2 border-gray-200 p-1 mb-2 bg-white inline-flex items-center justify-center">
                        <div className="w-full h-full bg-gray-100 grid grid-cols-4 gap-0.5">
                            {Array.from({ length: 16 }).map((_, i) => (
                                <div key={i} className={`bg-gray-400 ${Math.random() > 0.5 ? 'opacity-100' : 'opacity-0'}`} />
                            ))}
                        </div>
                    </div>
                    <p className="text-[8px] font-bold text-gray-500 uppercase tracking-widest">VERIFIED</p>
                </div>
            </div>
        </div>
    );
};
